### ISSUE TITLE
Compilation issues under 1.43.0 nightly

### ISSUE THREAD

**Issue by pskopnik** [hsivonen/encoding_rs#49]
I've encountered a compilation issue when building under 1.43.0 nightly of the rust toolchain. I noticed the problem when building the dependent [orjson][orjson] which uses the nightly toolchain for compilation.

I don't know much about rust, but it seems that an error occurs within a macro and the rust compiler subsequently panics.

I was able to reproduce the issue with the following commands, the features are the ones used by orjson. I'm filing this issue here, as I don't quite understand what is happening with regards to macros, user code and compiler code.

```shell
$ docker run --rm -it --entrypoint /bin/bash konstin2/maturin:master
(docker) $ git clone https://github.com/hsivonen/encoding_rs.git
(docker) $ cd encoding_rs/
(docker) $ git checkout v0.8.22
(docker) $ echo nightly > rust-toolchain
(docker) $ cargo --version
cargo 1.43.0-nightly (e02974078 2020-02-18)
(docker) $ rustc --version
rustc 1.43.0-nightly (7760cd0fb 2020-02-19)
(docker) $ RUST_BACKTRACE=full cargo build --features simd-accel --no-default-features
...
```

`--verbose` does not give much more information. `-Z macro-backtrace` does not seem to a valid flag.

<details>
<summary><code>cargo build</code> output</summary>

```
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: latest update on 2020-02-20, rust version 1.43.0-nightly (7760cd0fb 2020-02-19)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'rust-docs'
info: installing component 'rust-std'
info: installing component 'rustc'
info: installing component 'rustfmt'
    Updating crates.io index
  Downloaded packed_simd v0.3.3
   Compiling packed_simd v0.3.3
   Compiling encoding_rs v0.8.22 (/io/encoding_rs)
   Compiling cfg-if v0.1.10
warning: unused label
   --> src/macros.rs:878:41
    |
878 |   ...                   'innermost: loop {
    |                         ^^^^^^^^^^
    | 
   ::: src/euc_jp.rs:77:5
    |
77  | /     euc_jp_decoder_functions!(
78  | |         {
79  | |             let trail_minus_offset = byte.wrapping_sub(0xA1);
80  | |             // Fast-track Hiragana (60% according to Lunde)
...   |
220 | |         handle
221 | |     );
    | |______- in this macro invocation
    |
    = note: `#[warn(unused_labels)]` on by default
    = note: this warning originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unused label
   --> src/macros.rs:878:41
    |
878 |   ...                   'innermost: loop {
    |                         ^^^^^^^^^^
    | 
   ::: src/euc_jp.rs:77:5
    |
77  | /     euc_jp_decoder_functions!(
78  | |         {
79  | |             let trail_minus_offset = byte.wrapping_sub(0xA1);
80  | |             // Fast-track Hiragana (60% according to Lunde)
...   |
220 | |         handle
221 | |     );
    | |______- in this macro invocation
    |
    = note: this warning originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unused label
   --> src/macros.rs:574:41
    |
574 |   ...                   'innermost: loop {
    |                         ^^^^^^^^^^
    | 
   ::: src/gb18030.rs:111:5
    |
111 | /     gb18030_decoder_functions!(
112 | |         {
113 | |             // If first is between 0x81 and 0xFE, inclusive,
114 | |             // subtract offset 0x81.
...   |
294 | |         handle,
295 | |         'outermost);
    | |____________________- in this macro invocation
    |
    = note: this warning originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unused label
   --> src/macros.rs:574:41
    |
574 |   ...                   'innermost: loop {
    |                         ^^^^^^^^^^
    | 
   ::: src/gb18030.rs:111:5
    |
111 | /     gb18030_decoder_functions!(
112 | |         {
113 | |             // If first is between 0x81 and 0xFE, inclusive,
114 | |             // subtract offset 0x81.
...   |
294 | |         handle,
295 | |         'outermost);
    | |____________________- in this macro invocation
    |
    = note: this warning originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unused label
   --> src/mem.rs:279:17
    |
279 |                 'inner: loop {
    |                 ^^^^^^

warning: `...` range patterns are deprecated
   --> src/mem.rs:743:26
    |
743 |                         0...0x7F => {
    |                          ^^^ help: use `..=` for an inclusive range
    |
    = note: `#[warn(ellipsis_inclusive_range_patterns)]` on by default

warning: `...` range patterns are deprecated
   --> src/mem.rs:749:29
    |
749 |                         0xC2...0xD5 => {
    |                             ^^^ help: use `..=` for an inclusive range

warning: `...` range patterns are deprecated
   --> src/mem.rs:770:36
    |
770 |                         0xE1 | 0xE3...0xEC | 0xEE => {
    |                                    ^^^ help: use `..=` for an inclusive range

warning: `...` range patterns are deprecated
   --> src/mem.rs:879:29
    |
879 |                         0xF1...0xF4 => {
    |                             ^^^ help: use `..=` for an inclusive range

warning: `...` range patterns are deprecated
   --> src/mem.rs:942:18
    |
942 |                 0...0x7F => {
    |                  ^^^ help: use `..=` for an inclusive range

warning: `...` range patterns are deprecated
   --> src/mem.rs:948:21
    |
948 |                 0xC2...0xD5 => {
    |                     ^^^ help: use `..=` for an inclusive range

warning: `...` range patterns are deprecated
   --> src/mem.rs:985:28
    |
985 |                 0xE1 | 0xE3...0xEC | 0xEE => {
    |                            ^^^ help: use `..=` for an inclusive range

warning: `...` range patterns are deprecated
    --> src/lib.rs:2686:29
     |
2686 |                         b'A'...b'Z' => {
     |                             ^^^ help: use `..=` for an inclusive range

warning: `...` range patterns are deprecated
    --> src/lib.rs:2691:29
     |
2691 |                         b'a'...b'z' | b'0'...b'9' | b'-' | b'_' | b':' | b'.' => {
     |                             ^^^ help: use `..=` for an inclusive range

warning: `...` range patterns are deprecated
    --> src/lib.rs:2691:43
     |
2691 |                         b'a'...b'z' | b'0'...b'9' | b'-' | b'_' | b':' | b'.' => {
     |                                           ^^^ help: use `..=` for an inclusive range

warning: `...` range patterns are deprecated
    --> src/lib.rs:2714:29
     |
2714 |                         b'A'...b'Z' => {
     |                             ^^^ help: use `..=` for an inclusive range

warning: `...` range patterns are deprecated
    --> src/lib.rs:2723:29
     |
2723 |                         b'a'...b'z' | b'0'...b'9' | b'-' | b'_' | b':' | b'.' => {
     |                             ^^^ help: use `..=` for an inclusive range

warning: `...` range patterns are deprecated
    --> src/lib.rs:2723:43
     |
2723 |                         b'a'...b'z' | b'0'...b'9' | b'-' | b'_' | b':' | b'.' => {
     |                                           ^^^ help: use `..=` for an inclusive range

warning: use of deprecated item 'std::mem::uninitialized': use `mem::MaybeUninit` instead
  --> src/simd_funcs.rs:19:20
   |
19 |     let mut simd = ::std::mem::uninitialized();
   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default

warning: use of deprecated item 'std::mem::uninitialized': use `mem::MaybeUninit` instead
  --> src/simd_funcs.rs:43:20
   |
43 |     let mut simd = ::std::mem::uninitialized();
   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^

warning: use of deprecated item 'std::mem::uninitialized': use `mem::MaybeUninit` instead
   --> src/handles.rs:113:30
    |
113 |             let mut u: u16 = ::std::mem::uninitialized();
    |                              ^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unnecessary `unsafe` block
  --> src/utf_8.rs:91:12
   |
91 |         if unsafe { likely(read + 4 <= src.len()) } {
   |            ^^^^^^ unnecessary `unsafe` block
   |
   = note: `#[warn(unused_unsafe)]` on by default

warning: unnecessary `unsafe` block
  --> src/utf_8.rs:98:20
   |
98 |                 if unsafe { likely(in_inclusive_range8(byte, 0xC2, 0xDF)) } {
   |                    ^^^^^^ unnecessary `unsafe` block

warning: unnecessary `unsafe` block
   --> src/utf_8.rs:107:24
    |
107 |                     if unsafe { likely(read + 4 <= src.len()) } {
    |                        ^^^^^^ unnecessary `unsafe` block

warning: unnecessary `unsafe` block
   --> src/utf_8.rs:117:20
    |
117 |                 if unsafe { likely(byte < 0xF0) } {
    |                    ^^^^^^ unnecessary `unsafe` block

warning: unnecessary `unsafe` block
   --> src/utf_8.rs:132:28
    |
132 |                         if unsafe { likely(read + 4 <= src.len()) } {
    |                            ^^^^^^ unnecessary `unsafe` block

warning: unnecessary `unsafe` block
   --> src/utf_8.rs:137:32
    |
137 | ...                   if unsafe { likely(byte < 0x80) } {
    |                          ^^^^^^ unnecessary `unsafe` block

warning: unnecessary `unsafe` block
   --> src/utf_8.rs:162:20
    |
162 |                 if unsafe { likely(read + 4 <= src.len()) } {
    |                    ^^^^^^ unnecessary `unsafe` block

warning: unnecessary `unsafe` block
   --> src/utf_8.rs:261:12
    |
261 |         if unsafe { likely(read + 4 <= src.len()) } {
    |            ^^^^^^ unnecessary `unsafe` block

warning: unnecessary `unsafe` block
   --> src/utf_8.rs:271:20
    |
271 |                 if unsafe { likely(in_inclusive_range8(byte, 0xC2, 0xDF)) } {
    |                    ^^^^^^ unnecessary `unsafe` block

warning: unnecessary `unsafe` block
   --> src/utf_8.rs:288:24
    |
288 |                     if unsafe { likely(read + 4 <= src.len()) } {
    |                        ^^^^^^ unnecessary `unsafe` block

warning: unnecessary `unsafe` block
   --> src/utf_8.rs:300:20
    |
300 |                 if unsafe { likely(byte < 0xF0) } {
    |                    ^^^^^^ unnecessary `unsafe` block

warning: unnecessary `unsafe` block
   --> src/utf_8.rs:323:28
    |
323 |                         if unsafe { likely(read + 4 <= src.len()) } {
    |                            ^^^^^^ unnecessary `unsafe` block

warning: unnecessary `unsafe` block
   --> src/utf_8.rs:328:32
    |
328 | ...                   if unsafe { likely(byte < 0x80) } {
    |                          ^^^^^^ unnecessary `unsafe` block

warning: unnecessary `unsafe` block
   --> src/utf_8.rs:370:20
    |
370 |                 if unsafe { likely(read + 4 <= src.len()) } {
    |                    ^^^^^^ unnecessary `unsafe` block

warning: unnecessary `unsafe` block
   --> src/utf_8.rs:657:20
    |
657 |                 if unsafe { likely(unit_minus_surrogate_start > (0xDFFF - 0xD800)) } {
    |                    ^^^^^^ unnecessary `unsafe` block

warning: unnecessary `unsafe` block
   --> src/utf_8.rs:668:20
    |
668 |                 if unsafe { likely(unit_minus_surrogate_start <= (0xDBFF - 0xD800)) } {
    |                    ^^^^^^ unnecessary `unsafe` block

warning: unnecessary `unsafe` block
   --> src/utf_8.rs:687:24
    |
687 |                     if unsafe { likely(second_minus_low_surrogate_start <= (0xDFFF - 0xDC00)) } {
    |                        ^^^^^^ unnecessary `unsafe` block

warning: unnecessary `unsafe` block
   --> src/utf_8.rs:729:16
    |
729 |             if unsafe { unlikely(unit < 0x80) } {
    |                ^^^^^^ unnecessary `unsafe` block

warning: unnecessary `unsafe` block
   --> src/mem.rs:913:32
    |
913 | ...                   if unsafe { unlikely(second == 0x90 || second == 0x9E) } {
    |                          ^^^^^^ unnecessary `unsafe` block

warning: unnecessary `unsafe` block
    --> src/mem.rs:1171:28
     |
1171 |                         if unsafe { unlikely(byte >= 0xD6) } {
     |                            ^^^^^^ unnecessary `unsafe` block

warning: unnecessary `unsafe` block
    --> src/mem.rs:1195:24
     |
1195 |                     if unsafe { unlikely(!in_inclusive_range8(byte, 0xE3, 0xEE) && byte != 0xE1) } {
     |                        ^^^^^^ unnecessary `unsafe` block

warning: unnecessary `unsafe` block
    --> src/mem.rs:1244:24
     |
1244 |                     if unsafe { unlikely(byte == 0xF0 && (second == 0x90 || second == 0x9E)) } {
     |                        ^^^^^^ unnecessary `unsafe` block

warning: unnecessary `unsafe` block
    --> src/mem.rs:1658:8
     |
1658 |     if unsafe { likely(read == src.len()) } {
     |        ^^^^^^ unnecessary `unsafe` block

error: internal compiler error: src/librustc_codegen_ssa/mir/block.rs:622: shuffle indices must be constant
   --> src/simd_funcs.rs:289:28
    |
289 |           let first: u8x16 = shuffle!(
    |  ____________________________^
290 | |             s,
291 | |             u8x16::splat(0),
292 | |             [0, 16, 1, 17, 2, 18, 3, 19, 4, 20, 5, 21, 6, 22, 7, 23]
293 | |         );
    | |_________^
    |
    = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

thread 'rustc' panicked at 'Box<Any>', <::std::macros::panic macros>:2:4
stack backtrace:
   0:     0x7fce48a8a634 - backtrace::backtrace::libunwind::trace::h0743ecf0c905ca1e
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1:     0x7fce48a8a634 - backtrace::backtrace::trace_unsynchronized::h0e046f0811b0ae4d
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2:     0x7fce48a8a634 - std::sys_common::backtrace::_print_fmt::h5fcd1fd3d0e5d79e
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x7fce48a8a634 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h85ffb53d56efd098
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x7fce48ac37dc - core::fmt::write::h231e5515e704e96b
                               at src/libcore/fmt/mod.rs:1052
   5:     0x7fce48a7bf97 - std::io::Write::write_fmt::h56f503f924d6c255
                               at src/libstd/io/mod.rs:1428
   6:     0x7fce48a8f425 - std::sys_common::backtrace::_print::hf64c641be26866a9
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x7fce48a8f425 - std::sys_common::backtrace::print::h16b5d561563c7498
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x7fce48a8f425 - std::panicking::default_hook::{{closure}}::h8363003bce1deb1a
                               at src/libstd/panicking.rs:204
   9:     0x7fce48a8f166 - std::panicking::default_hook::hb365b24076d7b200
                               at src/libstd/panicking.rs:224
  10:     0x7fce490f9c39 - rustc_driver::report_ice::h2624db039b9cfba9
  11:     0x7fce48a8fb55 - std::panicking::rust_panic_with_hook::h2adc1d4c38cb25af
                               at src/libstd/panicking.rs:474
  12:     0x7fce494cf363 - std::panicking::begin_panic::h6fca9fdb6d23f676
  13:     0x7fce493e488c - rustc_errors::HandlerInner::span_bug::h6840991938d37012
  14:     0x7fce493e4c40 - rustc_errors::Handler::span_bug::h107187c882152f33
  15:     0x7fce49478c69 - rustc::util::bug::opt_span_bug_fmt::{{closure}}::hf73fd7e05df26a89
  16:     0x7fce4947715b - rustc::ty::context::tls::with_opt::{{closure}}::h0c4fdf5a849e88e3
  17:     0x7fce49477106 - rustc::ty::context::tls::with_opt::h92cfac8e0dd8f2c9
  18:     0x7fce49478b58 - rustc::util::bug::opt_span_bug_fmt::haf8b4183f62d8df3
  19:     0x7fce49478b0a - rustc::util::bug::span_bug_fmt::h0be341af60d13d91
  20:     0x7fce49573f1a - <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold::h333c620e944c2a61
  21:     0x7fce495532cc - rustc_codegen_ssa::mir::block::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::codegen_call_terminator::h61b66235d798dc9e
  22:     0x7fce4954e212 - rustc_codegen_ssa::mir::block::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::codegen_block::h977ed6f45937d617
  23:     0x7fce4956055e - rustc_codegen_ssa::base::codegen_instance::h1faa821de1d9e487
  24:     0x7fce4947f6b5 - <rustc::mir::mono::MonoItem as rustc_codegen_ssa::mono_item::MonoItemExt>::define::h0b6bdfededc22107
  25:     0x7fce4940668a - rustc_codegen_llvm::base::compile_codegen_unit::module_codegen::h469c76d782c84352
  26:     0x7fce494b3227 - rustc::dep_graph::graph::DepGraph::with_task::h29956dbbd3cd6e7c
  27:     0x7fce49406254 - rustc_codegen_llvm::base::compile_codegen_unit::hc09ab7897a17060a
  28:     0x7fce4955d55a - rustc_codegen_ssa::base::codegen_crate::h80e90e6d82f0580d
  29:     0x7fce494f1715 - <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate::hbcef469c00126974
  30:     0x7fce492e0710 - rustc_session::utils::<impl rustc_session::session::Session>::time::h101a151e306dd79b
  31:     0x7fce4938b2ef - rustc_interface::passes::QueryContext::enter::hc499d446e1b9ab96
  32:     0x7fce492bbf4b - rustc_interface::queries::Queries::ongoing_codegen::h201d0ed995ada5da
  33:     0x7fce491632be - rustc_interface::interface::run_compiler_in_existing_thread_pool::hdde65f8eb6e34231
  34:     0x7fce4911d29d - scoped_tls::ScopedKey<T>::set::h774e12e87074d2a2
  35:     0x7fce49104d82 - syntax::attr::with_globals::hd6f4e6fb8aaadb66
  36:     0x7fce4911e963 - std::sys_common::backtrace::__rust_begin_short_backtrace::h2e517a7b74830ac8
  37:     0x7fce48aa1447 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  38:     0x7fce49164ef6 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h3814fa1c62419cc0
  39:     0x7fce48a6c31f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h8e917a822ffc0592
                               at /rustc/7760cd0fbbbf2c59a625e075a5bdfa88b8e30f8a/src/liballoc/boxed.rs:1017
  40:     0x7fce48a9fd50 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h8aa486ee72f31ff1
                               at /rustc/7760cd0fbbbf2c59a625e075a5bdfa88b8e30f8a/src/liballoc/boxed.rs:1017
  41:     0x7fce48a9fd50 - std::sys_common::thread::start_thread::h8407e13fad90fc7e
                               at src/libstd/sys_common/thread.rs:13
  42:     0x7fce48a9fd50 - std::sys::unix::thread::Thread::new::thread_start::h55e6429cb8ed2e9f
                               at src/libstd/sys/unix/thread.rs:80
  43:     0x7fce4880883d - start_thread
  44:     0x7fce48170fdd - clone

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.43.0-nightly (7760cd0fb 2020-02-19) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: aborting due to previous error

error: could not compile `encoding_rs`.

To learn more, run the command again with --verbose.

```

</details>

[orjson]: https://github.com/ijl/orjson

**Comment by pskopnik** [comment]
/cc @ijl

I'm not sure how you're building orjson while avoiding this issue. Do you have any idea what would lead to this?

**Comment by ijl** [comment]
The last release was built using the 2020-02-18 nightly, so this was introduced in the 2020-02-19 nightly. It's an internal compiler error, so you could open an issue with the same traceback in https://github.com/rust-lang/rust. You can in the meantime use a previous nightly to build.

**Comment by pskopnik** [comment]
Thanks ijl, I can confirm that this issue does not occur with channel `nightly-2020-02-19` and starts appearing with channel `nightly-2020-02-20`.

```shell
(docker) $ echo nightly-2020-02-19 > rust-toolchain
(docker) $ cargo --version
cargo 1.43.0-nightly (3c53211c3 2020-02-07)
(docker) $ rustc --version
rustc 1.43.0-nightly (e620d0f33 2020-02-18)
```

**Comment by hsivonen** [comment]
For me:

Works: rustc 1.43.0-nightly (5e7af4669 2020-02-16)
Fails: rustc 1.43.0-nightly (7760cd0fb 2020-02-19)

**Comment by pskopnik** [comment]
@hsivonen, would you like to file the internal compiler error upstream? I don't know anything about how macros work and what a minimal example could be.

**Comment by hsivonen** [comment]
I'll file.

**Comment by hsivonen** [comment]
[Filed.](https://github.com/rust-lang/rust/issues/69313) Thanks for the head-up!

**Comment by pskopnik** [comment]
Great :+1: 
Thanks for the fast responses ilj, hsivonen!

Feel free to close this whenever you deem appropriate.

**Comment by ijl** [comment]
This was fixed with nightly-2020-02-22.

**Comment by hsivonen** [comment]
Confirmed fixed.
